### ISSUE TITLE
Save function does not work in ml.dtw Max Object

### ISSUE THREAD

**Issue by balandinodidonato** [cmuartfab/ml-lib#107]
To reproduce:
- open `ml.dtw.maxhelp`
- run all the process as indicate into the `ml.dtw.maxhelp` patch

Expected
- I can save the added data in a defined directory

Actual
- I get an error from the max window which says that this function is not supported. `error: ml.dtw: messages with the selector 'save' are not supported`

**Comment by jamiebullock** [comment]
Hi. The correct message is "write". Does the help file say "save"? If so, can you correct it and submit a pull request?

**Comment by balandinodidonato** [comment]
Sure!

**Comment by balandinodidonato** [comment]
Hi @jamiebullock do you wanted to say a 'Push' request? Can you give me the access to do that?

**Comment by equilet** [comment]
https://help.github.com/articles/creating-a-pull-request/
https://help.github.com/articles/using-pull-requests/

**Comment by balandinodidonato** [comment]
Pull request: https://github.com/cmuartfab/ml-lib/pull/109
