### ISSUE TITLE
Load function does not work in ml.dtw Max Object

### ISSUE THREAD

**Issue by balandinodidonato** [cmuartfab/ml-lib#108]
To reproduce:
- open ml.dtw.maxhelp
- run all the process as indicate into the ml.dtw.maxhelp patch

Expected
- I can load the added data in a defined directory

Actual
- I get an error from the max window which says that this function is not supported.

I suppose is the same error described in the issue  #107.

**Comment by jamiebullock** [comment]
Yup, this is another documentation bug. Should be "read" not "load". Likewise, a pull request would be appreciated.

**Comment by balandinodidonato** [comment]
https://github.com/cmuartfab/ml-lib/pull/109
