### ISSUE TITLE
pd externals for arm7

### ISSUE THREAD

**Issue by batchku** [cmuartfab/ml-lib#113]
could we make a new release to also include arm7 pd externals, compatible with the raspberry pi 2?

**Comment by jamiebullock** [comment]
I'll look into this ASAP.

**Comment by batchku** [comment]
hi jamie,
just got this.
thanks a lot fot taking a look.
we have some very exciting potential demos (would be great for NIME) that
need this.
we also direly need ports of the externals that work on android and iOS for
puredata

would you please give me a sense of how difficult this is or how i can help?

thanks,
ali

**Comment by jamiebullock** [comment]
The new build system (in develop and master) works on RPi and an RPi build is included in both 0.16.1 and 0.16.2. 

It would be good to set up a build server including all these platforms as per #118
