### ISSUE TITLE
ml.svm slows down max 7 interface

### ISSUE THREAD

**Issue by batchku** [cmuartfab/ml-lib#116]
i just tested the latest release (0.16.1) on max 7.0.3 (32-bit).
the external loads fine and functions.
however, i noticed that once i go into classification mode, the interface slows down a lot.  more disconcerting, when i left the patch running for 2 minutes and put max in the background (to start typing this message) max became unresponsive.

**Comment by jamiebullock** [comment]
Hmm.. OK, I'll take a look. I have plenty of time to work on this over the next few days.
