### ISSUE TITLE
compile pure data externals for linux (64bits)

### ISSUE THREAD

**Issue by eLandon** [cmuartfab/ml-lib#121]
Hi, 

I'm very interested in testing your toolkit, but I can't find how to compile from source. 
Following the BUILD.md instructions : downloaded 0.16.2 source, installed flext, compiled GTR ok, but I'm stuck at "cd to the ml-lib/build/flext directory", as the directory doesn't exist (only macosx/ml.xcodeproj)
Searching through the issue tracker I understand the build system might have changed since 0.16, so the instructions seems outdated.
I'm aware of #118 , just wondering if there would be a way for me to build that for testing in the meantime. I'd happily share the result !
I'm on ubuntu 15.10 64bits

**Comment by jamiebullock** [comment]
Hi, thanks for the report. I'll look into it ASAP

**Comment by LambdaFred** [comment]
Hi, 
same problem as eLandon, still waiting for the requested build/flext folder in source code as said in the BUILD.md file so that no chance to compile for Pd Linux.

**Comment by jamiebullock** [comment]
Hi,

Those build instructions are actually out-of-date. It should be a lot simpler now.

Just `cd build` and then `make` should build ml.lib on Linux

You will need to pull the latest code from the `develop` branch as I just fixed a few build errors

Let me know any issues.

**Comment by FredVoisin** [comment]
Hello,
thank you for the feedback, I ran until the file ml_names.o seems is missing :
`$ make
g++ -fdata-sections -ffunction-sections -O2 -std=c++11 -I../vendor/flext/source -I../vendor/grt/GRT -I../vendor/pd -I../sources -DFLEXT_SYS=2 -DFLEXT_INLINE -DFLEXT_USE_CMEM -DFLEXT_ATTRIBUTES=1 -DFLEXT_USE_HEX_SETUP_NAME -c ../sources/ml_base.cpp -o ../sources/ml_base.o
g++ -fdata-sections -ffunction-sections -O2 -std=c++11 -I../vendor/flext/source -I../vendor/grt/GRT -I../vendor/pd -I../sources -DFLEXT_SYS=2 -DFLEXT_INLINE -DFLEXT_USE_CMEM -DFLEXT_ATTRIBUTES=1 -DFLEXT_USE_HEX_SETUP_NAME -c ../sources/ml_formatter.cpp -o ../sources/ml_formatter.o
make: *** No rule to make target '../sources/ml_names.o', needed by 'all'. Arrêt.`

Did I forget something ?

**Comment by FredVoisin** [comment]
So, in the develop branch I took the missing ml_names.cpp from the master branch which tells an error about string in namespace 'std' in ml_names.h at lines 16 and after. I'm starting to debug, may be you'll go faster ?

**Comment by jamiebullock** [comment]
@FredVoisin yes, thanks for the input. But I believe I've now fixed this. I just need to push the changes :)

**Comment by jamiebullock** [comment]
OK, this *should* now be fixed. It's building on Linux for me here. Can you test and let me know?

**Comment by FredVoisin** [comment]
so, it's OK for the first three cpp, until ml_doc.cpp which is OK.
Then, g++ -c ml_doc_populate.cpp failed to generate .o with error about 'HMM_EGODIC' is not a member of GRT.
May be the branch of GRT I compiled from was not the good one (I took the grt master branch) ?

**Comment by jamiebullock** [comment]
@FredVoisin Right, you don't need to pull down your GRT as it's included in the ml-lib repository as a submodule. This should guarantee that you're building against a compatible version of GRT since the submodule points to a specific commit in the upstream repo. To get GRT (and indeed Flext), you need to clean out anything you added manually and then do a `git submodule update --init`. This should pull down the relevant submodules

**Comment by eLandon** [comment]
Hi,
Been following with great interest the latest discussions, thanks for the wrok !
But, just tried with submodules activated, and got (sorry, in french)

/usr/bin/ld: ../vendor/grt/GRT/CoreModules/GRTBase.o: réadressage de R_X86_64_32S en vertu de « _ZTVN3GRT3LogE » ne peut être utilisé lors de la création d'un objet partagé; recompilez avec -fPIC
../vendor/grt/GRT/CoreModules/GRTBase.o : erreur lors de l'ajout de symboles : Mauvaise valeur
collect2: error: ld returned 1 exit status

**Comment by FredVoisin** [comment]
yes,  it's going better but same error by here, after 'g++ -shared -Wl,--gc-sections ... o ../sources/classification/ml_adaboost.pd_linux',  but with some variation:
/usr/bin/ld: ../vendor/grt/GRT/PostProcessingModules/ClassLabelTimeoutFilter.o: réadressage de R_X86_64_32S en vertu de «ZTVN3GRT28RegisterPostProcessingModuleINS_23ClassLabelTimeoutFilterEEE » ne peut être utilisé lors de la création d'un objet partagé; recompilez avec -fPIC
../vendor/grt/GRT/PostProcessingModules/ClassLabelTimeoutFilter.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:99: recipe for target '../sources/classification/ml_adaboost.pd_linux' failed
make: *** [../sources/classification/ml_adaboost.pd_linux] Error 1

**Comment by jamiebullock** [comment]
Ah right, these are separate issues appearing, but now the "64bit" in the issue title becomes relevant!

I don't have a 64-bit Linux to test on, so before I make changes can one of you try:

`make CFLAGS+="-fPIC"`

**Comment by eLandon** [comment]
Same error here with the fPIC flag
did "make clean" and "git pull" before, not sure if I need to pull submodules ?

**Comment by jamiebullock** [comment]
@eLandon Hmm... can you paste the compiler line before the error into this thread? I want to check -fPIC is actually getting included, since this is what your error relates to.

**Comment by eLandon** [comment]
yes of course, I think it's exactly the same as before

/usr/bin/ld: ../vendor/grt/GRT/CoreModules/GRTBase.o: réadressage de R_X86_64_32S en vertu de « _ZTVN3GRT3LogE » ne peut être utilisé lors de la création d'un objet partagé; recompilez avec -fPIC
../vendor/grt/GRT/CoreModules/GRTBase.o : erreur lors de l'ajout de symboles : Mauvaise valeur
collect2: error: ld returned 1 exit status
Makefile:99 : la recette pour la cible « ../sources/classification/ml_adaboost.pd_linux » a échouée
make: *** [../sources/classification/ml_adaboost.pd_linux] Erreur 1

**Comment by eLandon** [comment]
So it seems passing -fPIC option wasn't taken into account this way isn't it ?

**Comment by jamiebullock** [comment]
@eLandon sorry, my mistake (trying to do too many things at once). It should of course be `make CPPFLAGS+=-fPIC`. Be sure to do a `make clean` first.

If that still doesn't add -fPIC to the compiler flags, then you can edit the Makefile and add the -fPIC manually to the CPPFLAGS before -O2

Let me know how it goes.

**Comment by eLandon** [comment]
No problem, you're already really kind to spend time like this !
Sorry I can't help regarding compilation flags, I sometimes tweak makefiles but I'm really not into compilation instructions.
So "make CPPFLAGS+=-fPIC" didn't work, had another error in adaboost saying it didn't find flext .h (can do the try again if you want the exact error output)
Adding the option in the make file compiled successfully, nice !
I followed with make install, this copied all of the .pd_linux files into build/build folder, I copied the example pd file in testing/ but the objects won't create.
Note that I'm under pd vanilla, not extended (that is deprecated), so perhaps there is some config to do on the pure data part. But maybe this is another thread ?

Thanks a lot for all the effort, if there's anything I can do for help I will be pleased (like creating a vanilla compatible, commented example as a start !)

**Comment by jamiebullock** [comment]
@eLandon Yes, I'm closing this as the original issue is resolved. Can you raise a separate one about the objects not loading, with the precise error given in Pd. It would be useful to enable "Verbose" logging in the Pd console for the most information. Testing is in itself helpful!
