### ISSUE TITLE
mlp read message load data but not model 

### ISSUE THREAD

**Issue by FredVoisin** [cmuartfab/ml-lib#136]
Hi Jamie,
had good times with the mlp.
write message is ok, data and model written in text files :-)
I don't succeed in loading a previously stored model : after 'read' ( /tmp/model or even /tmp/model.model ), the model is not correctly  reloaded : in regression mode, mapping is wrong and output values are very different when playing same data as the ones used to train, with very high contrasts (close to 0 or to 1).
Then, the mlp requires to be retrained by using only the message 'train' since the read message has successfully read the saved training data (so that 'write' and 'read' are not usefull and the mlp usable only on the fly (I can not manage such a play when the learning process may take 20 mn ;-)
I'm actually using ml.mlp with Max7 and Mountain Lion.

**Comment by jamiebullock** [comment]
Hi Fred. Does the file model.model actually get served by "write"? If so, would you mind sending me the file?

**Comment by FredVoisin** [comment]
yes, I did : write /tmp/mlp7instru1
data and model attached.
[mlp7instru1.zip](https://github.com/cmuartfab/ml-lib/files/1142651/mlp7instru1.zip)

**Comment by FredVoisin** [comment]
by chance this mlp7instru1  take just around 1 mn to learn !

**Comment by federicoVisi** [comment]
Hi Jamie,
I have encountered a similar issue with ml.svm. 'write' saves both .data and .model files just fine, although I can only read the .data file and then re-train the model while I can't load the .model file directly. I attached both files in the the zip below, hope this helps.
Cheers,
Federico

[testML.zip](https://github.com/cmuartfab/ml-lib/files/1222419/testML.zip)

**Comment by jamiebullock** [comment]
Thanks @federicoVisi I will take a look at this
