### ISSUE TITLE
mlp crashes PureData upon mapping

### ISSUE THREAD

**Issue by sbassoon** [cmuartfab/ml-lib#137]
Hey all,

Just wanted to document that attempting to map data using [ml.mlp] in Pd version 0.47-1, from mllib 0.17.0 alpha causes the program to immediately crash to desktop. I've tried editing the settings for the mlp, thinking perhaps something was set incorrectly. I've tried adding lots and very little training data, thinking my sets were the wrong size.

The mlp can add training data, train a model, output the model and data to text, and clear the training data and model, but the problem is when trying to send a map message to the mlp in order to get an output.

OS: MacOS Sierra 10.12.6

**Comment by jamiebullock** [comment]
Thanks for raising this. I'll take a look at it.

**Comment by jamiebullock** [comment]
Hi @sbassoon. Sorry for the delay. Can you try the latest release and let me know if it resolves your issue: https://github.com/cmuartfab/ml-lib/releases/tag/0.18.0

**Comment by jamiebullock** [comment]
Closing as fixed in 0.18.0

**Comment by sbassoon** [comment]
Hi @jamiebullock -- sorry for the delay! Verified that the fix works in Pd 0.48-1. Thank you for fixing this!
