### ISSUE TITLE
Building for Linux - no ml.linux_pd generated

### ISSUE THREAD

**Issue by graphographer** [cmuartfab/ml-lib#139]
I cannot load anything from the library without this file, it seems.

Also, the documentation should mention that libpd is a dependency, or perhaps it can just be included in the vendors directory.

Otherwise, everything appears to build fine on my RPi 2 / Stretch.

**Comment by jamiebullock** [comment]
Hi. libPd actually *isn't* a dependency. I'm not sure why it ended up getting linked in the Makefile, but it certainly isn't needed. I've now pushed some updates which remove these as well as fixing other stuff for Linux.

To build you need to do two things:

```
make
make install
```

The `make install` will create a `build` subdirectory with all the externals in.

If you want to change that install directory you can do:

`make install ML_INSTALL_DIR=/usr/local/lib/extra`

Or whatever you like. Let me know if this now works for you.

**Comment by graphographer** [comment]
I think that did it, thank you! I'm not sure, however, whether it is actually necessary to specify "-lib ml" in the startup flags?

Are there any example patches for training I can look at? Or rather, where is the best place to ask questions like this? Otherwise, I'm going to try to start throwing some data at ml.dtw and see what happens.

**Comment by jamiebullock** [comment]
Hi. GitHub is fine for questions. It’s probably best to start each question as a new issue so we can close them when they’re a answered.

Perhaps you already discovered this but there’s now an ml-lib-help.zip in releases with a few help files. If you take a look at the [ml.svm help patch](https://github.com/cmuartfab/ml-lib/tree/develop/documentation/help/pd) that should give you a good idea how to use all the other objects. 

There’s no need to pass `-lib ml` to Pd. This is only needed if you’ve built ml.lib as a library.

**Comment by jamiebullock** [comment]
There’s also a full object and parameter list [here](http://cmuartfab.github.io/ml-lib/)
