### ISSUE TITLE
Can't Find Externals

### ISSUE THREAD

**Issue by goodguyben** [cmuartfab/ml-lib#146]
I am quite new to Max. I am not able to find the externals (.mxo) files inthe library. Would I have to compile anything to obtain the .mxo file?

Thanks

**Comment by jamiebullock** [comment]
Hi, the releases can be found here: https://github.com/cmuartfab/ml-lib/releases

If you download the ml-0.18.0-alpha-OSX64 zip, you can open that and inside the Folder `Max` contains the externals
