### ISSUE TITLE
All-in-one documentation page

### ISSUE THREAD

**Issue by batchku** [cmuartfab/ml-lib#59]
i'd like a document (in text format is find, or on github) that just lists every object, every message it takes, and a description of what that message does and how its arguments should be formatted.

do we have such a document already?

presumably there's a way to build it into the max external so the documentation is built into the max help ecosystem...

**Comment by jamiebullock** [comment]
I *think* this issue was resolved by the introduction of the [class reference](http://cmuartfab.github.io/ml-lib/), therefore closing.
