### ISSUE TITLE
our pd helpfiles in pd-extended 0.43.4 not working

### ISSUE THREAD

**Issue by batchku** [cmuartfab/ml-lib#72]
i just tried opening the new ml.svm pd helpfile in pd extended and it didn't work:
1.  the ml lib didn't load even though it's int he pd searchpath
2.  the "patcher" (i.e. sub patch) that i added called "test" isn't found; as if it's an abstraction not a sub patch.

any ideas?

**Comment by jamiebullock** [comment]
Hi Ali, can you still reproduce this problem, or can we close the issue now?
