### ISSUE TITLE
ml.svm and list size limits in PD

### ISSUE THREAD

**Issue by batchku** [cmuartfab/ml-lib#94]
i'm finding that the "add" method for ml.svm fails if the list is larger than 255 items.
in this case, it doesn't complain, it reports the change to the new input list size, like this:

ml.svm: new input vector size, adjusting num_inputs to 257

but then keeps reporting that on subsequent "add" messages with the same size list.

ml.svm: new input vector size, adjusting num_inputs to 257
ml.svm: new input vector size, adjusting num_inputs to 257
ml.svm: new input vector size, adjusting num_inputs to 257

then when you train, it says:

error: ml.svm: no observations added, use 'add' to add training data

as if you haven't sent any feature vectors in.
is this a pd thing?

ali

**Comment by meq-hth** [comment]
hello. so any news about this bug? where this limitation comes from? 
thanks very much for your library, great work. we are having so much fun here!.

**Comment by jamiebullock** [comment]
Thanks for the reminder! I'll take a look today. @meq-hth So are you using ml.lib at Montpellier, any examples?

**Comment by meq-hth** [comment]
hello! yep we are trying it!. the problem is ...now we need more than 256 inputs . talking about examples. i can help doing help files for pd if you want.

**Comment by batchku** [comment]
Hello,

thank you Meq; pd help files would be wonderful and much appreciated!

-ali

**Comment by meq-hth** [comment]
Thnx!!!!!! :0)



On Tue, Jun 14, 2016 at 5:35 PM +0200, "Jamie Bullock" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #94<https://github.com/cmuartfab/ml-lib/issues/94>.
