### ISSUE TITLE
ml.lib 64bits version

### ISSUE THREAD

**Issue by davidcroft** [cmuartfab/ml-lib#99]
I seems that current ml-lib is 32bits only, is there any 64bits version for pd and max? Or do I miss something if there is already one? Thanks.

**Comment by jamiebullock** [comment]
@davidcroft I'm picking up this issue that was raised 3+ years ago! If you're still using ml.lib, are you still having this issue. Actually, on Mac, ml.lib is now 64-bits only. What platform are you on?
